owner: ZapYo-Ltd
repo: uptime

sites:
  - name: ZapYo Ltd Website
    url: https://zapyo.uk
  - name: OnezCloud Status
    url: https://status.onezcloud.uk
  - name: UK Buzz
    url: https://ukbuzz.uk
  - name: Will Young
    url: https://willyoung.uk
  - name: The Young Onez Ltd
    url: https://theyoungonez.uk
  - name: Ibraheem Dulmeer
    url: https://www.ibraheemdulmeer.com
  - name: Park Homes Law
    url: https://parkhomeslaw.com
  - name: Holiday Park Law
    url: https://www.holidayparklaw.com
  - name: Lease Barristers
    url: https://leasebarristers.com
  - name: Rent Repayment Law
    url: https://rentrepaymentlaw.com
  - name: Park Homes Legal UK
    url: https://parkhomeslegal.uk
  - name: The Angel Inn
    url: https://theangelinn.uk
  - name: Sweetstay
    url: https://sweetstay.uk
  - name: Wrangle Village
    url: https://wranglevillage.uk

assignees:
  - bigdopeywill

status-website:
  cname: status.onezcloud.uk
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: OnezCloud Uptime
  introTitle: "**OnezCloud Uptime** – Monitoring by ZapYo Ltd"
  introMessage: OnezCloud Uptime is a service provided by ZapYo Ltd, offering real-time monitoring of our digital services and key client platforms. Outages and disruptions will be displayed here as they happen. Powered by [Upptime](https://github.com/upptime/upptime) and GitHub Actions.
  navbar:
    - title: Status
      href: /
    - title: OnezCloud
      href: https://onezcloud.uk
    - title: ZapYo Ltd
      href: https://zapyo.uk
    - title: GitHub
      href: https://github.com/ZapYo-Ltd/uptime
