# Change these first
owner: ZapYo-Ltd
repo: OnezCloud-Status

sites:
  - name: Park Homes Law
    url: https://parkhomeslaw.com

status-website:
  cname: status.onezcloud.uk
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: OneCloud Uptime
  introTitle: "**OnezCloud Uptime** – Your Digital Peace of Mind"
  introMessage: Welcome to our real-time status page. We continuously monitor the availability of our services. If there are any issues, they'll be reported here. Powered by [Upptime](https://github.com/upptime/upptime) and GitHub Actions.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
