owner: ZapYo-Ltd
repo: CloudZap

sites:
  - name: ZapYo Ltd Website
    url: https://zapyo.uk
  - name: OnezCloud
    url: https://onezcloud.uk
  - name: CloudZap (Web Monitor)
    url: https://cloudzap.onezcloud.uk
  - name: Ibraheem Dulmeer
    url: https://www.ibraheemdulmeer.com
  - name: Park Homes Law
    url: https://parkhomeslaw.com
  - name: Holiday Park Law
    url: https://www.holidayparklaw.com
  - name: Lease Barristers
    url: https://leasebarristers.com
  - name: Rent Repayment Law
    url: https://rentrepaymentlaw.com
  - name: Park Homes Legal UK
    url: https://parkhomeslegal.uk
  - name: UK Buzz
    url: https://ukbuzz.uk
  - name: Will Young
    url: https://willyoung.uk
  - name: The Young Onez Ltd
    url: https://theyoungonez.uk
  - name: The Angel Inn
    url: https://theangelinn.uk
  - name: Sweetstay
    url: https://sweetstay.uk
  - name: Wrangle Village
    url: https://wranglevillage.uk


assignees:
  - bigdopeywill

status-website:
  cname: cloudzap.onezcloud.uk
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: CloudZap
  introTitle: "**CloudZap** – Uptime Monitoring by OnezCloud"
  introMessage: >
    CloudZap is a status monitoring system operated by ZapYo Ltd under the OnezCloud platform.
    It provides real-time visibility into the uptime and performance of our services and those of key partners.
    Any service disruptions or outages will appear here.
    Powered by [Upptime](https://github.com/upptime/upptime) and GitHub Actions.
    ⚡️ Monitoring the cloud, one zap at a time.
  navbar:
    - title: Status
      href: /
    - title: OnezCloud
      href: https://onezcloud.uk
    - title: ZapYo Ltd
      href: https://zapyo.uk
    - title: GitHub
      href: https://github.com/ZapYo-Ltd/CloudZap

