owner: WillsWay-Ltd
repo: WillsWay-Webcare-Site-Monitor

sites:
  - name: WillsWay Ltd
    url: https://willsway.uk
  - name: WillsWebcare (Web Monitor)
    url: https://cloudzap.zapsphere.uk
  - name: Ibraheem Dulmeer
    url: https://www.ibraheemdulmeer.com
  - name: Park Homes Law
    url: https://parkhomeslaw.com
  - name: Holiday Park Law
    url: https://www.holidayparklaw.com
  - name: Lease Barristers
    url: https://leasebarristers.com
  - name: Rent Repayment Law
    url: https://rentrepaymentlaw.com
  - name: Will Young
    url: https://willyoung.uk
  - name: The Angel Inn
    url: https://theangelinn.uk


assignees:
  - bigdopeywill

skipDeleteIssues: true

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"

status-website:
  cname: cloudzap.zapsphere.uk
  logoUrl: https://zapsphere.uk/CloudZap.svg
  faviconSvg: https://zapsphere.uk/CloudZap.svg
  theme: light
  name: CloudZap
  introTitle: "**CloudZap** – Uptime Monitoring by ZapSphere"
  introMessage: >
    CloudZap is a status monitoring system operated by ZapYo Ltd under the ZapSphere platform.
    It provides real-time visibility into the uptime and performance of our services and those of key partners.
    Any service disruptions or outages will appear here.
    Powered by [Upptime](https://github.com/upptime/upptime) and GitHub Actions.
    ⚡️ Monitoring the cloud, one zap at a time.
  navbar:
    - title: Status
      href: /
    - title: ZapSphere
      href: https://zapsphere.uk
    - title: ZapYo Ltd
      href: https://zapyo.uk
    - title: GitHub
      href: https://github.com/ZapYo-Ltd/CloudZap

