owner: WillsWay-Ltd
repo: WillsWay-Webcare-Site-Monitor

sites:
  - name: WillsWay Ltd
    url: https://willsway.uk
  - name: WillsWebcare (Web Monitor)
    url: https://cloudzap.zapsphere.uk
  - name: Ibraheem Dulmeer
    url: https://www.ibraheemdulmeer.com
  - name: Park Homes Law
    url: https://parkhomeslaw.com
  - name: Holiday Park Law
    url: https://www.holidayparklaw.com
  - name: Lease Barristers
    url: https://leasebarristers.com
  - name: Rent Repayment Law
    url: https://rentrepaymentlaw.com
  - name: Will Young
    url: https://willyoung.uk
  - name: The Angel Inn
    url: https://theangelinn.uk


assignees:
  - bigdopeywill

skipDeleteIssues: true

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"

status-website:
  cname: status.willsway.uk
  logoUrl: https://willsway.uk/brand-bits/WillsWay_WebCare_Logo_500x500px.svg
  faviconSvg: https://willsway.uk/brand-bits/WillsWay_WebCare_Logo_500x500px.svg
  theme: light
  name: WillsWay Webcare
  introTitle: "**WillsWay WebCare** – Live Domain Uptime Status"
  introMessage: >
  This is the official status page for services managed by **WillsWay WebCare**.
  It provides real-time visibility into website uptime, monitoring, and platform performance.
  Any service incidents, maintenance, or disruptions will be posted here as they occur.
  Powered by [Upptime](https://github.com/upptime/upptime) and GitHub Actions.
  ⚡ Keeping websites healthy, reliable, and online.
  navbar:
    - title: Status
      href: /
    - title: WillsWay Ltd
      href: https://willsway.uk
    - title: GitHub
      href: https://github.com/WillsWay-Ltd/WillsWay-Webcare-Site-Monitor
